name: iron
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'iron'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'iron'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_iron:
    name: iron
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    steps:
      - name: Checkout LVR2
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile LVR2 in ROS 2 iron WS
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: iron
          ROS_REPO: main
          AFTER_SCRIPT: cd ~/target_ws && ./build/lvr2/bin/lvr2_reconstruct src/lvr2/dat/scan.pts
